# Generated by Django 3.0.6 on 2020-09-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('OBSERVATION', 'OBSERVATION'), ('VISIT', 'VISIT'), ('SOLVED', 'SOLVED'), ('PENDING', 'PENDING'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('State Government', 'State Government'), ('Individual', 'Individual'), ('Central Government', 'Central Government'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Pubic Institution', 'Pubic Institution'), ('Foreign Embassy', 'Foreign Embassy'), ('Public Utilities', 'Public Utilities'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Service', 'Service'), ('PT', 'PT'), ('BB Over Wifi', 'BB Over Wifi'), ('VPT', 'VPT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Voter ID Card', 'Voter ID Card'), ('Passport', 'Passport'), ('PAN Card', 'PAN Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Government of India', 'Government of India'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Voter ID Card', 'Voter ID Card'), ('Passport', 'Passport'), ('PAN Card', 'PAN Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Government of India', 'Government of India'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
    ]
