# Generated by Django 3.0.6 on 2020-09-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Disconnected', 'Disconnected'), ('Complain', 'Complain'), ('Live', 'Live'), ('InProgress', 'Inprogress'), ('Suspended', 'Suspended'), ('Restored', 'Restored')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installation2',
            name='status',
            field=models.CharField(blank=True, choices=[('Disconnected', 'Disconnected'), ('Complain', 'Complain'), ('Live', 'Live'), ('InProgress', 'Inprogress'), ('Suspended', 'Suspended'), ('Restored', 'Restored')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='my',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('OBSERVATION', 'OBSERVATION'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('PT', 'PT'), ('VPT', 'VPT'), ('Pubic Institution', 'Pubic Institution'), ('Central Government', 'Central Government'), ('Foreign Embassy', 'Foreign Embassy'), ('BB Over Wifi', 'BB Over Wifi'), ('Service', 'Service'), ('Public Utilities', 'Public Utilities'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('State Government', 'State Government'), ('Individual', 'Individual')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MISS', 'MISS'), ('MS', 'MS'), ('DR', 'DR'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('PAN Card', 'PAN Card'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Passport Authority', 'Passport Authority'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('PAN Card', 'PAN Card'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Passport Authority', 'Passport Authority'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='accounttype',
            field=models.CharField(choices=[('PT', 'PT'), ('VPT', 'VPT'), ('Pubic Institution', 'Pubic Institution'), ('Central Government', 'Central Government'), ('Foreign Embassy', 'Foreign Embassy'), ('BB Over Wifi', 'BB Over Wifi'), ('Service', 'Service'), ('Public Utilities', 'Public Utilities'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('State Government', 'State Government'), ('Individual', 'Individual')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='billmedia',
            field=models.CharField(choices=[('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='lastname',
            field=models.CharField(choices=[('MISS', 'MISS'), ('MS', 'MS'), ('DR', 'DR'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poa',
            field=models.CharField(choices=[('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('PAN Card', 'PAN Card'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poaby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Passport Authority', 'Passport Authority'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poi',
            field=models.CharField(choices=[('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('PAN Card', 'PAN Card'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poiby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Passport Authority', 'Passport Authority'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('Suspended', 'Suspended'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
    ]
