# Generated by Django 3.0.6 on 2020-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Progress', 'Progress'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('PT', 'PT'), ('Pubic Institution', 'Pubic Institution'), ('BB Over Wifi', 'BB Over Wifi'), ('VPT', 'VPT'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Service', 'Service'), ('State Government', 'State Government'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('Public Utilities', 'Public Utilities')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('DR', 'DR'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
