# Generated by Django 3.0.5 on 2020-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='status',
            field=models.CharField(choices=[('Reg', 'Registered'), ('Progress', 'In Process'), ('NOC', 'No Coverage'), ('NA', 'not applicable'), ('Pend', 'Pending'), ('OK', 'OK')], default='Reg', max_length=10),
        ),
    ]
