# Generated by Django 3.0.6 on 2020-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200816_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Progress', 'Progress'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('BILL DISPUTE', 'BILL DISPUTE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('CABLE CUT', 'CABLE CUT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
