# Generated by Django 3.0.6 on 2020-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200919_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Installed', 'Installed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('SOLVED', 'SOLVED'), ('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('BB Over Wifi', 'BB Over Wifi'), ('State Government', 'State Government'), ('Foreign Embassy', 'Foreign Embassy'), ('Pubic Institution', 'Pubic Institution'), ('VPT', 'VPT'), ('Central Government', 'Central Government'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Service', 'Service'), ('PT', 'PT'), ('Individual', 'Individual'), ('Public Utilities', 'Public Utilities'), ('MMVC PostPaid', 'MMVC PostPaid')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('DR', 'DR'), ('MISS', 'MISS'), ('MR', 'MR'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Passport', 'Passport'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Goverment ID Card', 'Goverment ID Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('PAN Card', 'PAN Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Passport', 'Passport'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Goverment ID Card', 'Goverment ID Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('PAN Card', 'PAN Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
