# Generated by Django 3.0.6 on 2020-09-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20200921_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Suspended', 'Suspended'), ('Complain', 'Complain'), ('InProgress', 'Inprogress'), ('Live', 'Live'), ('Restored', 'Restored'), ('Disconnected', 'Disconnected')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installation2',
            name='status',
            field=models.CharField(blank=True, choices=[('Suspended', 'Suspended'), ('Complain', 'Complain'), ('InProgress', 'Inprogress'), ('Live', 'Live'), ('Restored', 'Restored'), ('Disconnected', 'Disconnected')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='my',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('N.A.', 'N.A.'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Foreign Embassy', 'Foreign Embassy'), ('State Government', 'State Government'), ('Public Utilities', 'Public Utilities'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Service', 'Service'), ('PT', 'PT'), ('BB Over Wifi', 'BB Over Wifi'), ('Individual', 'Individual'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('Pubic Institution', 'Pubic Institution'), ('VPT', 'VPT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('DR', 'DR'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='accounttype',
            field=models.CharField(choices=[('Foreign Embassy', 'Foreign Embassy'), ('State Government', 'State Government'), ('Public Utilities', 'Public Utilities'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Service', 'Service'), ('PT', 'PT'), ('BB Over Wifi', 'BB Over Wifi'), ('Individual', 'Individual'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('Pubic Institution', 'Pubic Institution'), ('VPT', 'VPT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('DR', 'DR'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poa',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poaby',
            field=models.CharField(choices=[('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poi',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poiby',
            field=models.CharField(choices=[('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='accounttype',
            field=models.CharField(choices=[('Foreign Embassy', 'Foreign Embassy'), ('State Government', 'State Government'), ('Public Utilities', 'Public Utilities'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Service', 'Service'), ('PT', 'PT'), ('BB Over Wifi', 'BB Over Wifi'), ('Individual', 'Individual'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('Pubic Institution', 'Pubic Institution'), ('VPT', 'VPT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('DR', 'DR'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poa',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poaby',
            field=models.CharField(choices=[('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poi',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poiby',
            field=models.CharField(choices=[('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Suspended', 'Suspended'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
    ]
