# Generated by Django 3.0.6 on 2020-09-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20200904_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Installed', 'Installed'), ('Pending', 'Pending'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('SOLVED', 'SOLVED'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('SOLVED', 'SOLVED'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
