# Generated by Django 3.0.6 on 2020-08-16 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travello', '0003_auto_20200816_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Newcomplain1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60)),
                ('accountno', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True)),
                ('subject', models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True)),
                ('note', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=200, null=True)),
                ('date_solved', models.DateTimeField(null=True)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('user1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
