# Generated by Django 3.0.6 on 2020-09-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200922_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('InProgress', 'Inprogress'), ('Suspended', 'Suspended'), ('Restored', 'Restored'), ('Disconnected', 'Disconnected'), ('Complain', 'Complain'), ('Live', 'Live')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installation2',
            name='status',
            field=models.CharField(blank=True, choices=[('InProgress', 'Inprogress'), ('Suspended', 'Suspended'), ('Restored', 'Restored'), ('Disconnected', 'Disconnected'), ('Complain', 'Complain'), ('Live', 'Live')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='my',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Retired BSNL Employee', 'Retired BSNL Employee'), ('Central Government', 'Central Government'), ('PT', 'PT'), ('MMVC PostPaid', 'MMVC PostPaid'), ('BB Over Wifi', 'BB Over Wifi'), ('Pubic Institution', 'Pubic Institution'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual'), ('State Government', 'State Government'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Service', 'Service'), ('VPT', 'VPT'), ('Public Utilities', 'Public Utilities')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Driving Licence', 'Driving Licence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Driving Licence', 'Driving Licence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='accounttype',
            field=models.CharField(choices=[('Retired BSNL Employee', 'Retired BSNL Employee'), ('Central Government', 'Central Government'), ('PT', 'PT'), ('MMVC PostPaid', 'MMVC PostPaid'), ('BB Over Wifi', 'BB Over Wifi'), ('Pubic Institution', 'Pubic Institution'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual'), ('State Government', 'State Government'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Service', 'Service'), ('VPT', 'VPT'), ('Public Utilities', 'Public Utilities')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poa',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Driving Licence', 'Driving Licence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poaby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poi',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Driving Licence', 'Driving Licence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poiby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='accounttype',
            field=models.CharField(choices=[('Retired BSNL Employee', 'Retired BSNL Employee'), ('Central Government', 'Central Government'), ('PT', 'PT'), ('MMVC PostPaid', 'MMVC PostPaid'), ('BB Over Wifi', 'BB Over Wifi'), ('Pubic Institution', 'Pubic Institution'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual'), ('State Government', 'State Government'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Service', 'Service'), ('VPT', 'VPT'), ('Public Utilities', 'Public Utilities')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poa',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Driving Licence', 'Driving Licence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poaby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poi',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Driving Licence', 'Driving Licence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poiby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Suspended', 'Suspended'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
    ]
