# Generated by Django 3.0.6 on 2020-09-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200905_2113'),
        ('travello', '0003_auto_20200906_0712'),
    ]

    operations = [
    ]
