# Generated by Django 3.0.6 on 2020-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200919_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='cablingtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('CABLE CUT', 'CABLE CUT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('VISIT', 'VISIT'), ('SOLVED', 'SOLVED'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('CABLE CUT', 'CABLE CUT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('MMVC PostPaid', 'MMVC PostPaid'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual'), ('Service', 'Service'), ('BB Over Wifi', 'BB Over Wifi'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Public Utilities', 'Public Utilities'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('VPT', 'VPT'), ('Pubic Institution', 'Pubic Institution'), ('State Government', 'State Government'), ('Central Government', 'Central Government'), ('PT', 'PT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('POSTPAID', 'POSTPAID'), ('PREPAID', 'PREPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('MS', 'MS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Voter ID Card', 'Voter ID Card'), ('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Government of India', 'Government of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('RTO', 'RTO'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Voter ID Card', 'Voter ID Card'), ('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Government of India', 'Government of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('RTO', 'RTO'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
    ]
