# Generated by Django 3.0.6 on 2020-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20200915_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Installed', 'Installed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('N.A.', 'N.A.'), ('SOLVED', 'SOLVED'), ('OBSERVATION', 'OBSERVATION'), ('VISIT', 'VISIT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Service', 'Service'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('State Government', 'State Government'), ('Pubic Institution', 'Pubic Institution'), ('Foreign Embassy', 'Foreign Embassy'), ('Central Government', 'Central Government'), ('VPT', 'VPT'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('MMVC PostPaid', 'MMVC PostPaid'), ('PT', 'PT'), ('BB Over Wifi', 'BB Over Wifi'), ('Individual', 'Individual'), ('Public Utilities', 'Public Utilities')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('MR', 'MR'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
    ]
