# Generated by Django 3.0.6 on 2020-07-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_feasable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
