# Generated by Django 3.0.6 on 2020-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20200923_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='feedbacktime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Disconnected', 'Disconnected'), ('InProgress', 'Inprogress'), ('Suspended', 'Suspended'), ('Live', 'Live'), ('Restored', 'Restored'), ('Complain', 'Complain')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installation2',
            name='status',
            field=models.CharField(blank=True, choices=[('Disconnected', 'Disconnected'), ('InProgress', 'Inprogress'), ('Suspended', 'Suspended'), ('Live', 'Live'), ('Restored', 'Restored'), ('Complain', 'Complain')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='my',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Pending', 'Pending'), ('Progress', 'Progress'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Pending', 'Pending'), ('Progress', 'Progress'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'SOLVED'), ('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('VPT', 'VPT'), ('State Government', 'State Government'), ('Pubic Institution', 'Pubic Institution'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Service', 'Service'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Public Utilities', 'Public Utilities'), ('PT', 'PT'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Individual', 'Individual'), ('Foreign Embassy', 'Foreign Embassy'), ('BB Over Wifi', 'BB Over Wifi'), ('Central Government', 'Central Government')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('ERO', 'ERO'), ('RTO', 'RTO'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('ERO', 'ERO'), ('RTO', 'RTO'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='accounttype',
            field=models.CharField(choices=[('VPT', 'VPT'), ('State Government', 'State Government'), ('Pubic Institution', 'Pubic Institution'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Service', 'Service'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Public Utilities', 'Public Utilities'), ('PT', 'PT'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Individual', 'Individual'), ('Foreign Embassy', 'Foreign Embassy'), ('BB Over Wifi', 'BB Over Wifi'), ('Central Government', 'Central Government')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='customertype',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poa',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poaby',
            field=models.CharField(choices=[('ERO', 'ERO'), ('RTO', 'RTO'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poi',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='poiby',
            field=models.CharField(choices=[('ERO', 'ERO'), ('RTO', 'RTO'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer2',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='accounttype',
            field=models.CharField(choices=[('VPT', 'VPT'), ('State Government', 'State Government'), ('Pubic Institution', 'Pubic Institution'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Service', 'Service'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Public Utilities', 'Public Utilities'), ('PT', 'PT'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Individual', 'Individual'), ('Foreign Embassy', 'Foreign Embassy'), ('BB Over Wifi', 'BB Over Wifi'), ('Central Government', 'Central Government')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='customertype',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poa',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poaby',
            field=models.CharField(choices=[('ERO', 'ERO'), ('RTO', 'RTO'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poi',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='poiby',
            field=models.CharField(choices=[('ERO', 'ERO'), ('RTO', 'RTO'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer3',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary'), ('Suspended', 'Suspended')], max_length=200, null=True),
        ),
    ]
