# Generated by Django 3.0.6 on 2020-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='benefits',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.CharField(max_length=150),
        ),
    ]
