# Generated by Django 3.0.6 on 2020-08-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20200817_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Installed', 'Installed'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='date_solved',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('N.A.', 'N.A.'), ('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
