# Generated by Django 3.0.6 on 2020-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20200904_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Pending', 'Pending'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('VISIT', 'VISIT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('VISIT', 'VISIT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
    ]
