# Generated by Django 3.0.5 on 2020-08-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200731_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=50)),
                ('mymobile', models.CharField(max_length=20)),
                ('referalname', models.CharField(max_length=50)),
                ('referalmobile', models.CharField(max_length=20)),
                ('referalemail', models.EmailField(max_length=60)),
                ('referaladdress', models.TextField()),
                ('message', models.TextField()),
                ('category', models.CharField(max_length=25)),
                ('contacttime', models.CharField(max_length=30)),
                ('date_reg1', models.DateTimeField(auto_now_add=True, verbose_name='date_reg1')),
            ],
        ),
    ]
