# Generated by Django 3.0.5 on 2020-08-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200806_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
