# Generated by Django 3.0.6 on 2020-09-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200915_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Goverment ID Card', 'Goverment ID Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Voter ID Card', 'Voter ID Card'), ('PAN Card', 'PAN Card'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Passport Authority', 'Passport Authority'), ('Government of India', 'Government of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Income Tax Department', 'Income Tax Department'), ('RTO', 'RTO'), ('ERO', 'ERO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='poidate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='poiref',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='poitype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Progress', 'Progress'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('N.A.', 'N.A.'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED'), ('OBSERVATION', 'OBSERVATION')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Pubic Institution', 'Pubic Institution'), ('VPT', 'VPT'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('Service', 'Service'), ('PT', 'PT'), ('Public Utilities', 'Public Utilities'), ('Individual', 'Individual'), ('Foreign Embassy', 'Foreign Embassy'), ('State Government', 'State Government'), ('BB Over Wifi', 'BB Over Wifi'), ('Retired BSNL Employee', 'Retired BSNL Employee')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
