# Generated by Django 3.0.6 on 2020-09-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200919_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='timewo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('PENDING', 'PENDING'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Public Utilities', 'Public Utilities'), ('Individual', 'Individual'), ('Pubic Institution', 'Pubic Institution'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('PT', 'PT'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Service', 'Service'), ('BB Over Wifi', 'BB Over Wifi'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('Foreign Embassy', 'Foreign Embassy'), ('VPT', 'VPT'), ('State Government', 'State Government')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('POSTPAID', 'POSTPAID'), ('PREPAID', 'PREPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('DR', 'DR'), ('MISS', 'MISS'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Government of India', 'Government of India'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Government of India', 'Government of India'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
