# Generated by Django 3.0.6 on 2020-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20200810_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Installed', 'Installed'), ('Progress', 'Progress'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
    ]
