# Generated by Django 3.0.6 on 2020-09-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_auto_20200916_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='baddress',
            field=models.CharField(default='Pune', max_length=500),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bcity',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bdistrict',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bexchangecode',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bgstin',
            field=models.CharField(default='27', max_length=15),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bhouseno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='blandmark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='blocaility',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bpincode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bstate',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bsublocaility',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='bvillage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING'), ('VISIT', 'VISIT'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Retired BSNL Employee', 'Retired BSNL Employee'), ('Pubic Institution', 'Pubic Institution'), ('Central Government', 'Central Government'), ('BB Over Wifi', 'BB Over Wifi'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('VPT', 'VPT'), ('Foreign Embassy', 'Foreign Embassy'), ('PT', 'PT'), ('Service', 'Service'), ('State Government', 'State Government'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Individual', 'Individual'), ('Public Utilities', 'Public Utilities')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('DR', 'DR'), ('MS', 'MS'), ('MISS', 'MISS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Goverment ID Card', 'Goverment ID Card'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Passport', 'Passport'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('CGHS/EGHS Card', 'CGHS/EGHS Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('UIDAI Government Of India', 'UIDAI Government Of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Goverment ID Card', 'Goverment ID Card'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Passport', 'Passport'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('CGHS/EGHS Card', 'CGHS/EGHS Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('UIDAI Government Of India', 'UIDAI Government Of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
