# Generated by Django 3.0.6 on 2020-09-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_auto_20200916_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'SOLVED'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT'), ('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Bharat Air Fibre', 'Bharat Air Fibre'), ('PT', 'PT'), ('Service', 'Service'), ('Public Utilities', 'Public Utilities'), ('Individual', 'Individual'), ('MMVC PostPaid', 'MMVC PostPaid'), ('VPT', 'VPT'), ('Central Government', 'Central Government'), ('State Government', 'State Government'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Foreign Embassy', 'Foreign Embassy'), ('Pubic Institution', 'Pubic Institution'), ('BB Over Wifi', 'BB Over Wifi')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='address',
            field=models.CharField(default='Pune', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='baddress',
            field=models.CharField(blank=True, default='Pune', max_length=500),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bcity',
            field=models.CharField(blank=True, default='Pune', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bdistrict',
            field=models.CharField(blank=True, default='Pune', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bexchangecode',
            field=models.CharField(blank=True, default='Pune', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bhouseno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='blandmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='blocaility',
            field=models.CharField(blank=True, default='Pune', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bpincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bsublocaility',
            field=models.CharField(blank=True, default='Pune', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bvillage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('POSTPAID', 'POSTPAID'), ('PREPAID', 'PREPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MISS', 'MISS'), ('MR', 'MR'), ('DR', 'DR'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='mobileno',
            field=models.CharField(default='123', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='mobileno1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Passport', 'Passport'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Goverment ID Card', 'Goverment ID Card'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Government of India', 'Government of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poadate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Passport', 'Passport'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Goverment ID Card', 'Goverment ID Card'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Government of India', 'Government of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poidate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='adharcardno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='drivinglicenceno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='electricityno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='mobileno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='panno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
