# Generated by Django 3.0.6 on 2020-09-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_auto_20200920_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Live', 'Live'), ('Disconnected', 'Disconnected'), ('Restored', 'Restored'), ('Suspended', 'Suspended'), ('InProgress', 'Inprogress'), ('Complain', 'Complain')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('OPEN', 'OPEN'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING'), ('N.A.', 'N.A.'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Central Government', 'Central Government'), ('Individual', 'Individual'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Public Utilities', 'Public Utilities'), ('Service', 'Service'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('VPT', 'VPT'), ('Pubic Institution', 'Pubic Institution'), ('Foreign Embassy', 'Foreign Embassy'), ('BB Over Wifi', 'BB Over Wifi'), ('MMVC PostPaid', 'MMVC PostPaid'), ('State Government', 'State Government'), ('PT', 'PT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('POSTPAID', 'POSTPAID'), ('PREPAID', 'PREPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('MS', 'MS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Goverment ID Card', 'Goverment ID Card'), ('Passport', 'Passport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('UIDAI Government Of India', 'UIDAI Government Of India'), ('Income Tax Department', 'Income Tax Department'), ('Government of India', 'Government of India'), ('RTO', 'RTO'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('ERO', 'ERO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Goverment ID Card', 'Goverment ID Card'), ('Passport', 'Passport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('UIDAI Government Of India', 'UIDAI Government Of India'), ('Income Tax Department', 'Income Tax Department'), ('Government of India', 'Government of India'), ('RTO', 'RTO'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('ERO', 'ERO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
