# Generated by Django 3.0.6 on 2020-09-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_auto_20200917_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Installed', 'Installed'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('VISIT', 'VISIT'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('VPT', 'VPT'), ('Central Government', 'Central Government'), ('Foreign Embassy', 'Foreign Embassy'), ('Service', 'Service'), ('PT', 'PT'), ('Public Utilities', 'Public Utilities'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('State Government', 'State Government'), ('Pubic Institution', 'Pubic Institution'), ('BB Over Wifi', 'BB Over Wifi'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Individual', 'Individual')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='adharcardno',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='drivinglicenceno',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='electricityno',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Bimonthly', 'Bimonthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('DR', 'DR'), ('MISS', 'MISS'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='panno',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Government of India', 'Government of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('RTO', 'RTO'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Government of India', 'Government of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
