# Generated by Django 3.0.6 on 2020-09-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_auto_20200920_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Complain', 'Complain'), ('Live', 'Live'), ('Disconnected', 'Disconnected'), ('Restored', 'Restored'), ('Suspended', 'Suspended'), ('InProgress', 'Inprogress')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('INPROGESS', 'INPROGRESS'), ('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('ROUTER SUPPORT', 'ROUTER SUPPORT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('N.A.', 'N.A.'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('ROUTER SUPPORT', 'ROUTER SUPPORT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('State Government', 'State Government'), ('MMVC PostPaid', 'MMVC PostPaid'), ('BB Over Wifi', 'BB Over Wifi'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Individual', 'Individual'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Pubic Institution', 'Pubic Institution'), ('Service', 'Service'), ('VPT', 'VPT'), ('Central Government', 'Central Government'), ('Public Utilities', 'Public Utilities'), ('Foreign Embassy', 'Foreign Embassy'), ('PT', 'PT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('EMAIL', 'EMAIL'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('DR', 'DR'), ('MR', 'MR'), ('MISS', 'MISS'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Goverment ID Card', 'Goverment ID Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('ERO', 'ERO'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Passport Authority', 'Passport Authority'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Goverment ID Card', 'Goverment ID Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('ERO', 'ERO'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Passport Authority', 'Passport Authority'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO')], max_length=100, null=True),
        ),
    ]
