# Generated by Django 3.0.6 on 2020-09-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_auto_20200906_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Installed', 'Installed'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('BILL DISPUTE', 'BILL DISPUTE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('BILL DISPUTE', 'BILL DISPUTE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
