# Generated by Django 3.0.6 on 2020-09-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_auto_20200920_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travello.Employee'),
        ),
        migrations.AddField(
            model_name='installation',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travello.Vendor'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Suspended', 'Suspended'), ('Restored', 'Restored'), ('Live', 'Live'), ('Disconnected', 'Disconnected'), ('Complain', 'Complain'), ('InProgress', 'Inprogress')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Installed', 'Installed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('OBSERVATION', 'OBSERVATION'), ('VISIT', 'VISIT'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('VPT', 'VPT'), ('Pubic Institution', 'Pubic Institution'), ('Central Government', 'Central Government'), ('Foreign Embassy', 'Foreign Embassy'), ('Public Utilities', 'Public Utilities'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Service', 'Service'), ('State Government', 'State Government'), ('PT', 'PT'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('BB Over Wifi', 'BB Over Wifi'), ('Individual', 'Individual'), ('MMVC PostPaid', 'MMVC PostPaid')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('DR', 'DR'), ('MS', 'MS'), ('MR', 'MR'), ('MISS', 'MISS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Goverment ID Card', 'Goverment ID Card'), ('Passport', 'Passport'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Voter ID Card', 'Voter ID Card'), ('Ration Card with Photo', 'Ration Card with Photo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Income Tax Department', 'Income Tax Department'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Goverment ID Card', 'Goverment ID Card'), ('Passport', 'Passport'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Voter ID Card', 'Voter ID Card'), ('Ration Card with Photo', 'Ration Card with Photo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('RTO', 'RTO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Income Tax Department', 'Income Tax Department'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary'), ('Suspended', 'Suspended')], max_length=200, null=True),
        ),
    ]
