# Generated by Django 3.0.6 on 2020-09-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_auto_20200917_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Bharat Air Fibre', 'Bharat Air Fibre'), ('VPT', 'VPT'), ('Central Government', 'Central Government'), ('Service', 'Service'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual'), ('BB Over Wifi', 'BB Over Wifi'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('State Government', 'State Government'), ('PT', 'PT'), ('Public Utilities', 'Public Utilities'), ('Pubic Institution', 'Pubic Institution')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MISS', 'MISS'), ('MS', 'MS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Voter ID Card', 'Voter ID Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Passport', 'Passport'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('PAN Card', 'PAN Card'), ('Goverment ID Card', 'Goverment ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Voter ID Card', 'Voter ID Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Passport', 'Passport'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('PAN Card', 'PAN Card'), ('Goverment ID Card', 'Goverment ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('RTO', 'RTO'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
