# Generated by Django 3.0.6 on 2020-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_auto_20200816_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
    ]
