# Generated by Django 3.0.6 on 2020-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_auto_20200920_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Complain', 'Complain'), ('Live', 'Live'), ('Disconnected', 'Disconnected'), ('InProgress', 'Inprogress'), ('Restored', 'Restored'), ('Suspended', 'Suspended')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Installed', 'Installed'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('PENDING', 'PENDING'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Retired BSNL Employee', 'Retired BSNL Employee'), ('BB Over Wifi', 'BB Over Wifi'), ('Foreign Embassy', 'Foreign Embassy'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Service', 'Service'), ('MMVC PostPaid', 'MMVC PostPaid'), ('State Government', 'State Government'), ('Pubic Institution', 'Pubic Institution'), ('Individual', 'Individual'), ('Public Utilities', 'Public Utilities'), ('Central Government', 'Central Government'), ('VPT', 'VPT'), ('PT', 'PT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('POSTPAID', 'POSTPAID'), ('PREPAID', 'PREPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('MR', 'MR'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Passport', 'Passport'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Goverment ID Card', 'Goverment ID Card'), ('Voter ID Card', 'Voter ID Card'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('PAN Card', 'PAN Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Ministry Of Defence', 'Ministry Of Defence'), ('RTO', 'RTO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Government of India', 'Government of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Driving Licence', 'Driving Licence'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Passport', 'Passport'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Goverment ID Card', 'Goverment ID Card'), ('Voter ID Card', 'Voter ID Card'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('PAN Card', 'PAN Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Ministry Of Defence', 'Ministry Of Defence'), ('RTO', 'RTO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Government of India', 'Government of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Suspended', 'Suspended')], max_length=200, null=True),
        ),
    ]
