# Generated by Django 3.0.6 on 2020-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0014_auto_20200808_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('C', 'Low Value items'), ('A', 'high value items'), ('B', 'Medium value items')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salesfaq',
            name='question',
            field=models.TextField(),
        ),
    ]
