# Generated by Django 3.0.6 on 2020-09-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200917_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned'), ('Working', 'Working')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Progress', 'Progress'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('BILL DISPUTE', 'BILL DISPUTE'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'SOLVED'), ('PENDING', 'PENDING'), ('OBSERVATION', 'OBSERVATION'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('BILL DISPUTE', 'BILL DISPUTE'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Service', 'Service'), ('Public Utilities', 'Public Utilities'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('PT', 'PT'), ('Individual', 'Individual'), ('Central Government', 'Central Government'), ('Pubic Institution', 'Pubic Institution'), ('MMVC PostPaid', 'MMVC PostPaid'), ('VPT', 'VPT'), ('BB Over Wifi', 'BB Over Wifi'), ('Foreign Embassy', 'Foreign Embassy'), ('State Government', 'State Government'), ('Retired BSNL Employee', 'Retired BSNL Employee')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='adharcardno',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Bimonthly', 'Bimonthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MISS', 'MISS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Voter ID Card', 'Voter ID Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('RTO', 'RTO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Voter ID Card', 'Voter ID Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('RTO', 'RTO'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
