# Generated by Django 3.0.6 on 2020-09-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200920_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Complain', 'Complain'), ('Live', 'Live'), ('Disconnected', 'Disconnected'), ('Suspended', 'Suspended'), ('InProgress', 'Inprogress'), ('Restored', 'Restored')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('OBSERVATION', 'OBSERVATION'), ('VISIT', 'VISIT'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('CABLE CUT', 'CABLE CUT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Bharat Air Fibre', 'Bharat Air Fibre'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('BB Over Wifi', 'BB Over Wifi'), ('Pubic Institution', 'Pubic Institution'), ('State Government', 'State Government'), ('Central Government', 'Central Government'), ('Service', 'Service'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Public Utilities', 'Public Utilities'), ('PT', 'PT'), ('VPT', 'VPT'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MISS', 'MISS'), ('MR', 'MR'), ('DR', 'DR'), ('MS', 'MS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Passport', 'Passport'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Income Tax Department', 'Income Tax Department'), ('Government of India', 'Government of India'), ('ERO', 'ERO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Driving Licence', 'Driving Licence'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Passport', 'Passport'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Village Panchayath', 'Village Panchayath'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Income Tax Department', 'Income Tax Department'), ('Government of India', 'Government of India'), ('ERO', 'ERO'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract'), ('Suspended', 'Suspended')], max_length=200, null=True),
        ),
    ]
