# Generated by Django 3.0.6 on 2020-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200816_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM')], max_length=200, null=True),
        ),
    ]
