# Generated by Django 3.0.6 on 2020-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_auto_20200907_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('INPROGESS', 'INPROGRESS'), ('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('VISIT', 'VISIT'), ('SOLVED', 'SOLVED'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
