# Generated by Django 3.0.6 on 2020-09-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_auto_20200917_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Progress', 'Progress'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('OPEN', 'OPEN'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'SOLVED'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Retired BSNL Employee', 'Retired BSNL Employee'), ('State Government', 'State Government'), ('Public Utilities', 'Public Utilities'), ('BB Over Wifi', 'BB Over Wifi'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Foreign Embassy', 'Foreign Embassy'), ('PT', 'PT'), ('Central Government', 'Central Government'), ('Service', 'Service'), ('Pubic Institution', 'Pubic Institution'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Individual', 'Individual'), ('VPT', 'VPT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('EMAIL', 'EMAIL'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='drivinglicenceno',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MISS', 'MISS'), ('MR', 'MR'), ('MS', 'MS'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='panno',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Driving Licence', 'Driving Licence'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Passport', 'Passport'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Voter ID Card', 'Voter ID Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Passport Authority', 'Passport Authority'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Driving Licence', 'Driving Licence'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Passport', 'Passport'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Voter ID Card', 'Voter ID Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Passport Authority', 'Passport Authority'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='uesrname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
