# Generated by Django 3.0.6 on 2020-09-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_auto_20200917_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Installed', 'Installed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'SOLVED'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING'), ('N.A.', 'N.A.'), ('VISIT', 'VISIT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('CABLE CUT', 'CABLE CUT'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Retired BSNL Employee', 'Retired BSNL Employee'), ('Service', 'Service'), ('Public Utilities', 'Public Utilities'), ('Central Government', 'Central Government'), ('State Government', 'State Government'), ('BB Over Wifi', 'BB Over Wifi'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Pubic Institution', 'Pubic Institution'), ('Foreign Embassy', 'Foreign Embassy'), ('Individual', 'Individual'), ('MMVC PostPaid', 'MMVC PostPaid'), ('VPT', 'VPT'), ('PT', 'PT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('POSTPAID', 'POSTPAID'), ('PREPAID', 'PREPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='electricityno',
            field=models.CharField(blank=True, default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Bimonthly', 'Bimonthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MISS', 'MISS'), ('MS', 'MS'), ('DR', 'DR'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('RTO', 'RTO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('PAN Card', 'PAN Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Passport', 'Passport'), ('Goverment ID Card', 'Goverment ID Card'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Government of India', 'Government of India'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Ministry Of Defence', 'Ministry Of Defence'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('RTO', 'RTO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
