# Generated by Django 3.0.6 on 2020-09-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_auto_20200907_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Pending', 'Pending'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('CABLE CUT', 'CABLE CUT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('N.A.', 'N.A.'), ('SOLVED', 'SOLVED'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('CABLE CUT', 'CABLE CUT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
