# Generated by Django 3.0.6 on 2020-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_auto_20200920_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='myassignment',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Disconnected', 'Disconnected'), ('Suspended', 'Suspended'), ('Complain', 'Complain'), ('Live', 'Live'), ('Restored', 'Restored'), ('InProgress', 'Inprogress')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('CABLE CUT', 'CABLE CUT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('BILL DISPUTE', 'BILL DISPUTE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Service', 'Service'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Public Utilities', 'Public Utilities'), ('State Government', 'State Government'), ('BB Over Wifi', 'BB Over Wifi'), ('VPT', 'VPT'), ('PT', 'PT'), ('Foreign Embassy', 'Foreign Embassy'), ('Pubic Institution', 'Pubic Institution'), ('Individual', 'Individual'), ('Bharat Air Fibre', 'Bharat Air Fibre')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MISS', 'MISS'), ('DR', 'DR'), ('MS', 'MS'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Passport', 'Passport'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Passport Authority', 'Passport Authority'), ('Village Panchayath', 'Village Panchayath'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Passport', 'Passport'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Goverment ID Card', 'Goverment ID Card'), ('PAN Card', 'PAN Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('ERO', 'ERO'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Passport Authority', 'Passport Authority'), ('Village Panchayath', 'Village Panchayath'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('The Central Govt Health Department', 'The Central Govt Health Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Suspended', 'Suspended'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
    ]
