# Generated by Django 3.0.5 on 2020-08-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_auto_20200809_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='category',
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Progress', 'Progress'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
