# Generated by Django 3.0.6 on 2020-09-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_auto_20200920_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='My',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Installed', 'Installed'), ('Progress', 'Progress'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Suspended', 'Suspended'), ('Restored', 'Restored'), ('Live', 'Live'), ('Complain', 'Complain'), ('InProgress', 'Inprogress'), ('Disconnected', 'Disconnected')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Progress', 'Progress'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('OBSERVATION', 'OBSERVATION'), ('SOLVED', 'SOLVED'), ('VISIT', 'VISIT'), ('PENDING', 'PENDING'), ('N.A.', 'N.A.')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('BILL DISPUTE', 'BILL DISPUTE'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('CABLE CUT', 'CABLE CUT'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('State Government', 'State Government'), ('Central Government', 'Central Government'), ('Public Utilities', 'Public Utilities'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Foreign Embassy', 'Foreign Embassy'), ('PT', 'PT'), ('Individual', 'Individual'), ('BB Over Wifi', 'BB Over Wifi'), ('Service', 'Service'), ('Pubic Institution', 'Pubic Institution'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('VPT', 'VPT')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('DR', 'DR'), ('MS', 'MS'), ('MISS', 'MISS'), ('MR', 'MR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Passport', 'Passport'), ('PAN Card', 'PAN Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Goverment ID Card', 'Goverment ID Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('ERO', 'ERO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Passport', 'Passport'), ('PAN Card', 'PAN Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Goverment ID Card', 'Goverment ID Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('ERO', 'ERO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Passport Authority', 'Passport Authority'), ('Ministry Of Defence', 'Ministry Of Defence'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Residental', 'Residental'), ('Business', 'Business')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Suspended', 'Suspended'), ('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Myassignment',
        ),
        migrations.AddField(
            model_name='my',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travello.Newcustomer'),
        ),
    ]
