# Generated by Django 3.0.5 on 2020-08-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_auto_20200809_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tags',
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Installed', 'Installed'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
    ]
