# Generated by Django 3.0.6 on 2020-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0019_auto_20200920_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('Temporary', 'Temporary'), ('OnContract', 'OnContract')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(blank=True, choices=[('Restored', 'Restored'), ('Complain', 'Complain'), ('InProgress', 'Inprogress'), ('Disconnected', 'Disconnected'), ('Live', 'Live'), ('Suspended', 'Suspended')], default='InProgress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='my',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Out for delivery', 'Out for delivery'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Slow Speed', 'Slow Speed'), ('No Connection', 'No Connection'), ('Billing Complant', 'Billing Complant'), ('Relocation', 'Relocation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('VISIT', 'VISIT'), ('N.A.', 'N.A.'), ('SOLVED', 'SOLVED'), ('OBSERVATION', 'OBSERVATION'), ('PENDING', 'PENDING')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('CABLE CUT', 'CABLE CUT'), ('BILL DISPUTE', 'BILL DISPUTE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Service', 'Service'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('PT', 'PT'), ('BB Over Wifi', 'BB Over Wifi'), ('Central Government', 'Central Government'), ('Pubic Institution', 'Pubic Institution'), ('Individual', 'Individual'), ('Public Utilities', 'Public Utilities'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('VPT', 'VPT'), ('Foreign Embassy', 'Foreign Embassy'), ('MMVC PostPaid', 'MMVC PostPaid'), ('State Government', 'State Government')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL'), ('Print Bill On Paper', 'Print Bill On Paper')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('DR', 'DR'), ('MR', 'MR'), ('MS', 'MS'), ('MISS', 'MISS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('UIDAI Government Of India', 'UIDAI Government Of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('PAN Card', 'PAN Card'), ('Driving Licence', 'Driving Licence'), ('Goverment ID Card', 'Goverment ID Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Passport', 'Passport'), ('Voter ID Card', 'Voter ID Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('The Central Govt Health Department', 'The Central Govt Health Department'), ('Government of India', 'Government of India'), ('Ministry Of Defence', 'Ministry Of Defence'), ('ERO', 'ERO'), ('Income Tax Department', 'Income Tax Department'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Village Panchayath', 'Village Panchayath'), ('Passport Authority', 'Passport Authority'), ('UIDAI Government Of India', 'UIDAI Government Of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='usage',
            field=models.CharField(choices=[('Business', 'Business'), ('Residental', 'Residental')], default='Residental', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Suspended', 'Suspended'), ('Working', 'Working'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
    ]
