# Generated by Django 3.0.6 on 2020-09-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0020_auto_20200917_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('OnContract', 'OnContract'), ('Working', 'Working'), ('Temporary', 'Temporary'), ('Resigned', 'Resigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Installed', 'Installed'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('INPROGESS', 'INPROGRESS'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('Billing Complant', 'Billing Complant'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'SOLVED'), ('VISIT', 'VISIT'), ('OBSERVATION', 'OBSERVATION'), ('N.A.', 'N.A.'), ('PENDING', 'PENDING')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('PASSWORD FORGOT', 'PASSWORD FORGOT'), ('BILL DISPUTE', 'BILL DISPUTE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('SLOW SPEED TEST', 'SLOW SPEED TEST')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('Foreign Embassy', 'Foreign Embassy'), ('Service', 'Service'), ('State Government', 'State Government'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('Individual', 'Individual'), ('PT', 'PT'), ('Public Utilities', 'Public Utilities'), ('Pubic Institution', 'Pubic Institution'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('BB Over Wifi', 'BB Over Wifi'), ('MMVC PostPaid', 'MMVC PostPaid'), ('VPT', 'VPT'), ('Central Government', 'Central Government')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='communicationmethod',
            field=models.CharField(choices=[('Email', 'Email'), ('Mobile', 'Mobile')], default='Email', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('POSTPAID', 'POSTPAID'), ('PREPAID', 'PREPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='customertype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='frequency',
            field=models.CharField(choices=[('Bimonthly', 'Bimonthly'), ('Monthly', 'Monthly')], default='Monthly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('MR', 'MR'), ('DR', 'DR'), ('MISS', 'MISS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Passport', 'Passport'), ('PAN Card', 'PAN Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Passport', 'Passport'), ('PAN Card', 'PAN Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Driving Licence', 'Driving Licence'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Voter ID Card', 'Voter ID Card'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Goverment ID Card', 'Goverment ID Card'), ('Ration Card with Photo', 'Ration Card with Photo'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('UIDAI Government Of India', 'UIDAI Government Of India'), ('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('Passport Authority', 'Passport Authority'), ('ERO', 'ERO'), ('Ministry Of Defence', 'Ministry Of Defence'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('Government of India', 'Government of India'), ('Income Tax Department', 'Income Tax Department'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
