# Generated by Django 3.0.6 on 2020-09-17 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travello', '0021_auto_20200917_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Resigned', 'Resigned'), ('OnContract', 'OnContract'), ('Temporary', 'Temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Progress', 'Progress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='status',
            field=models.CharField(choices=[('INPROGESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('OPEN', 'OPEN')], default='OPEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain',
            name='subject',
            field=models.CharField(choices=[('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PASSWORD FORGOT', 'PASSWORD FORGOT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='category',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('No Connection', 'No Connection'), ('Slow Speed', 'Slow Speed'), ('Billing Complant', 'Billing Complant')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='status',
            field=models.CharField(choices=[('N.A.', 'N.A.'), ('PENDING', 'PENDING'), ('VISIT', 'VISIT'), ('SOLVED', 'SOLVED'), ('OBSERVATION', 'OBSERVATION')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcomplain1',
            name='subject',
            field=models.CharField(choices=[('SLOW SPEED TEST', 'SLOW SPEED TEST'), ('FREQUENTLY DISCONNECT', 'FREQUENTLY DISCONNECT'), ('CABLE CUT', 'CABLE CUT'), ('UNABLE TO BROWSE', 'UNABLE TO BROWSE'), ('WEBSITE NOT OPENING', 'WEBSITE NOT OPENING'), ('BILL DISPUTE', 'BILL DISPUTE'), ('EQUIPEMENT PROBLEM', 'EQUIPEMENT PROBLEM'), ('PAYMENT PROBLEM', 'PAYMENT PROBLEM'), ('ROUTER SUPPORT', 'ROUTER SUPPORT'), ('PAYMENT NOT UPDATED', 'PAYMENT NOT UPDATED'), ('PASSWORD FORGOT', 'PASSWORD FORGOT')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='accounttype',
            field=models.CharField(choices=[('PT', 'PT'), ('Bharat Air Fibre', 'Bharat Air Fibre'), ('Pubic Institution', 'Pubic Institution'), ('Individual', 'Individual'), ('Public Utilities', 'Public Utilities'), ('MMVC PostPaid', 'MMVC PostPaid'), ('Central Government', 'Central Government'), ('BB Over Wifi', 'BB Over Wifi'), ('Foreign Embassy', 'Foreign Embassy'), ('Retired BSNL Employee', 'Retired BSNL Employee'), ('State Government', 'State Government'), ('VPT', 'VPT'), ('Service', 'Service')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='bccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billaccno',
            field=models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='billmedia',
            field=models.CharField(choices=[('Print Bill On Paper', 'Print Bill On Paper'), ('PAPER AND EMAIL', 'PAPER AND EMAIL'), ('EMAIL', 'EMAIL')], default='EMAIL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='ccategory',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], default='Urban', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='connectiontype',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('POSTPAID', 'POSTPAID')], default='POSTPAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='lastname',
            field=models.CharField(choices=[('MS', 'MS'), ('MISS', 'MISS'), ('MR', 'MR'), ('DR', 'DR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poa',
            field=models.CharField(choices=[('Goverment ID Card', 'Goverment ID Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Voter ID Card', 'Voter ID Card'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Ration Card with Photo', 'Ration Card with Photo'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('PAN Card', 'PAN Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poaby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('Ministry Of Defence', 'Ministry Of Defence'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Government of India', 'Government of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poi',
            field=models.CharField(choices=[('Goverment ID Card', 'Goverment ID Card'), ('Smart Card by CSD Defence', 'Smart Card by CSD Defence'), ('Voter ID Card', 'Voter ID Card'), ('Passport', 'Passport'), ('Unique Indentificationby Authority Of India', 'Unique Indentificationby Authority Of India'), ('Ration Card with Photo', 'Ration Card with Photo'), ('CGHS/EGHS Card', 'CGHS/EGHS Card'), ('Photo ID Card by Edu Institute', 'Photo ID Card by Edu Institute'), ('Photo ID by Village Panchayath', 'Photo ID by Village Panchayath'), ('Pass Book Of Bank or PO', 'Pass Book Of Bank or PO'), ('PAN Card', 'PAN Card'), ('Certificate Issued By MLA MP GR A Officer', 'Certificate Issued By MLA MP GR A Officer'), ('Driving Licence', 'Driving Licence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='poiby',
            field=models.CharField(choices=[('Village Panchayath', 'Village Panchayath'), ('RTO', 'RTO'), ('Issued By MLA MP GR A Officer', 'Issued By MLA MP GR A Officer'), ('Income Tax Department', 'Income Tax Department'), ('Ministry Of Defence', 'Ministry Of Defence'), ('The Central Govt Health Department', 'The Central Govt Health Department'), ('ERO', 'ERO'), ('Passport Authority', 'Passport Authority'), ('Bank Branch Manager or PO', 'Pass Book Of Bank or PO'), ('UIDAI Government Of India', 'UIDAI Government Of India'), ('Government of India', 'Government of India')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer9',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
