# Generated by Django 3.0.5 on 2020-05-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('mrp', models.IntegerField()),
                ('prp', models.IntegerField()),
                ('war', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('abc', models.CharField(max_length=1)),
                ('fms', models.CharField(max_length=1)),
                ('freezepur', models.BooleanField(default=False)),
                ('freezesales', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('hnscode', models.CharField(max_length=10)),
                ('gstper', models.IntegerField(default=18)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Uom')),
            ],
        ),
    ]
