# Generated by Django 3.0.5 on 2020-05-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='abc',
        ),
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('M', 'medium moving items'), ('F', 'fast moving items'), ('S', 'slow moving items')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gstper',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='hnscode',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
    ]
