# Generated by Django 3.0.5 on 2020-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200501_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc',
            field=models.CharField(choices=[('A', 'high value items'), ('B', 'Medium value items'), ('C', 'Low Value items')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gstper',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='prp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='war',
            field=models.IntegerField(default=1),
        ),
    ]
