# Generated by Django 3.0.5 on 2020-07-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200501_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('F', 'fast moving items'), ('M', 'medium moving items'), ('S', 'slow moving items')], default='M', max_length=1),
        ),
    ]
