# Generated by Django 3.0.5 on 2020-07-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20200728_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc',
            field=models.CharField(choices=[('A', 'high value items'), ('C', 'Low Value items'), ('B', 'Medium value items')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('M', 'medium moving items'), ('S', 'slow moving items'), ('F', 'fast moving items')], default='M', max_length=1),
        ),
    ]
