# Generated by Django 3.0.5 on 2020-07-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20200728_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('S', 'slow moving items'), ('M', 'medium moving items'), ('F', 'fast moving items')], default='M', max_length=1),
        ),
    ]
