# Generated by Django 3.0.5 on 2020-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20200728_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc',
            field=models.CharField(choices=[('B', 'Medium value items'), ('C', 'Low Value items'), ('A', 'high value items')], default='B', max_length=10),
        ),
    ]
