# Generated by Django 3.0.5 on 2020-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20200728_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc',
            field=models.CharField(choices=[('A', 'high value items'), ('B', 'Medium value items'), ('C', 'Low Value items')], default='B', max_length=10),
        ),
    ]
