# Generated by Django 3.0.6 on 2020-08-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_auto_20200806_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc',
            field=models.CharField(choices=[('B', 'Medium value items'), ('A', 'high value items'), ('C', 'Low Value items')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('F', 'fast moving items'), ('S', 'slow moving items'), ('M', 'medium moving items')], default='M', max_length=1),
        ),
    ]
