# Generated by Django 3.0.6 on 2020-08-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_auto_20200806_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('M', 'medium moving items'), ('S', 'slow moving items'), ('F', 'fast moving items')], default='M', max_length=1),
        ),
    ]
