# Generated by Django 3.0.6 on 2020-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20200806_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc',
            field=models.CharField(choices=[('B', 'Medium value items'), ('C', 'Low Value items'), ('A', 'high value items')], default='B', max_length=10),
        ),
    ]
