# Generated by Django 3.0.5 on 2020-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0127_auto_20200809_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('M', 'medium moving items'), ('S', 'slow moving items'), ('F', 'fast moving items')], default='M', max_length=1),
        ),
    ]
