# Generated by Django 3.0.6 on 2020-08-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0140_auto_20200815_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('S', 'slow moving items'), ('M', 'medium moving items'), ('F', 'fast moving items')], default='M', max_length=1),
        ),
    ]
