# Generated by Django 3.0.6 on 2020-08-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0178_auto_20200823_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc',
            field=models.CharField(choices=[('C', 'Low Value items'), ('B', 'Medium value items'), ('A', 'high value items')], default='B', max_length=10),
        ),
    ]
