# Generated by Django 3.0.6 on 2020-08-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0185_auto_20200824_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('F', 'fast moving items'), ('S', 'slow moving items'), ('M', 'medium moving items')], default='M', max_length=1),
        ),
    ]
