# Generated by Django 3.0.6 on 2020-08-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0187_auto_20200824_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fms',
            field=models.CharField(choices=[('M', 'medium moving items'), ('F', 'fast moving items'), ('S', 'slow moving items')], default='M', max_length=1),
        ),
    ]
